[project]
name = "yolo_runner"
version = "0.1"
description = "Project for running multiple YOLO versions as docker containers with http communication."

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]